# Generated by Django 2.2.12 on 2021-07-09 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizlapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answerTitle',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='gameTitle',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='questionTitle',
            new_name='title',
        ),
    ]
